### ISSUE TITLE
Doc!

### ISSUE THREAD

**Issue by taktikal17** [alekzhang/yelp_external_website_scraper#1]
Hi, 

Thanks for sharing your script!
Can you quickly summarize How to run properly your pharmacy_email.py ?

Thanks a lot!!!!!!

**Comment by alekzhang** [comment]
This is built using scrapy. After installing the prerequisites, you can run "scrapy crawl pharmacy_email -o out.csv -t csv" and see the results in out.csv

**Comment by taktikal17** [comment]
Thanks @alekzhang!

It works like charm with Python 3.4 too! :100:

**Comment by alekzhang** [comment]
Glad to hear it :))
